// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HELPiOS
{
	public partial class MainTabbarController : UITabBarController
	{
		public MainTabbarController (IntPtr handle) : base (handle)
		{
		}
	}
}
