// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HELPiOS
{
	public partial class MyBookingViewController : UIViewController
	{
		public MyBookingViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
