// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HELPiOS
{
	public partial class ResultViewController : UIViewController
	{
		public ResultViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
